Feature/rating and chars count
Froggy-G/ru-study-python pull request #2
Opened 2022-10-05 17:49 UTC by Froggy-G

2022-10-06 08:39 UTC, aleksandr-semenov-dbp requested changes

2022-10-06 08:39 UTC, aleksandr-semenov-dbp commented on exercises/map.py
> +            countries_count = len(movie['country'].split(','))
split() неудачный выбор функции для посчета запятых, она делает слишком много ненужного, включая аллокацию новых объектов, давай поищем что-то полегче

2022-10-07 10:42 UTC, Froggy-G commented on exercises/map.py
> +            countries_count = len(movie['country'].split(','))
заменил функцией count()

2022-10-07 14:20 UTC, aleksandr-semenov-dbp approved these changes

2022-10-07 21:06 UTC, merged